spring:
    application:
        name:board
    datasource:
        url: jdbc:h2:tcp://localhost/~/board;
        username: sa
        password:
        driver-class-name: org.h2.Driver
        output:
            ansi:
               enabled: ALWAYS

    sql:
        init:
            mode: always
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
        #        show_sql: true
                format_sql: true