---- 멤버 더미 데이터
--INSERT INTO member (member_id, name, password)
--VALUES (1, '홍길동', 'password123');
--
--INSERT INTO member (member_id, name, password)
--VALUES (2, '김영희', 'secure456');
--
---- 노트 더미 데이터
--INSERT INTO note (note_id, member_id, title, contents, created_at, view_count)
--VALUES (1, 1, '첫 번째 글', '홍길동의 글입니다.', CURRENT_TIMESTAMP, 0);
--
--INSERT INTO note (note_id, member_id, title, contents, created_at, view_count)
--VALUES (2, 1, '두 번째 글', '홍길동의 두 번째 글입니다.', CURRENT_TIMESTAMP, 0);
--
--INSERT INTO note (note_id, member_id, title, contents, created_at, view_count)
--VALUES (3, 2, '김영희의 글', '안녕하세요, 김영희입니다.', CURRENT_TIMESTAMP, 0);
--
---- ID 자동 증가 시퀀스 초기화 (H2에서만 가능)
--ALTER TABLE member ALTER COLUMN member_id RESTART WITH 3;
ALTER TABLE note ALTER COLUMN note_id RESTART WITH 4;
